# Deployment that uses secrets from Kubernetes Secret

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: $CI_ENVIRONMENT_SLUG
  template:
    metadata:
      labels:
        app: $CI_ENVIRONMENT_SLUG
    spec:
      containers:
      - name: app
        image: $CI_REGISTRY_IMAGE:$CI_REGISTRY_TAG
        ports:
        - containerPort: $HTTP_PORT

        # Method 1: Inject secrets as environment variables
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url

        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-password

        - name: EXTERNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: external-api-key

        # Method 2: Mount secrets as files
        volumeMounts:
        - name: secret-files
          mountPath: /etc/secrets
          readOnly: true

      volumes:
      - name: secret-files
        secret:
          secretName: app-secrets
          items:
          - key: database-url
            path: database-url.txt
          - key: external-api-key
            path: api-key.txt

# Secrets will be available as:
# - Environment variables: $DATABASE_URL, $DATABASE_PASSWORD, $EXTERNAL_API_KEY
# - Files: /etc/secrets/database-url.txt, /etc/secrets/api-key.txt
