# Kubernetes Secret template using Vault secrets from GitLab CI/CD
# This file is deployed BEFORE the deployment.yaml

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: $KUBE_NAMESPACE
type: Opaque
stringData:
  # Database credentials from Vault
  database-password: $DB_PASSWORD
  database-username: $DB_USERNAME
  database-host: $DB_HOST

  # API keys from Vault
  external-api-key: $EXTERNAL_API_KEY

  # Connection string (can be constructed from other secrets)
  database-url: "postgresql://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:5432/myapp"
