# Basic Kubernetes deployment template for Platon PaaS
# This file is processed by the 'deploy' script which substitutes CI/CD variables

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
    track: stable
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: $CI_ENVIRONMENT_SLUG
      track: stable
  template:
    metadata:
      labels:
        app: $CI_ENVIRONMENT_SLUG
        track: stable
    spec:
      containers:
      - name: app
        image: $CI_REGISTRY_IMAGE:$CI_REGISTRY_TAG
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: $HTTP_PORT
          protocol: TCP

        # Health checks
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

        # Resource limits
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

        # Environment variables (optional)
        # env:
        # - name: DATABASE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: app-secrets
        #       key: database-url
